# Generated by Django 4.2.4 on 2023-08-28 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_is_staff_alter_user_is_superuser_products"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Products",
        ),
    ]
